### PR TITLE
remove the role config. Simplify debug

### PR DESCRIPTION
**Pull request by supertoto29**
**Warning :** Before creating a pull request, make sure that it does not already exists in the [pull requests](../). Thank you.

## Description
Remove the role assignement in the proc. This help since we don't need to wait for the existence of the service in debug mode. I have made a shady move in the other branch to patch this. I changed the provider to assign the roles

## How has this been tested ?
Tested locally

## Checklist
- [x] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

### CODE REVIEW

**Review by 0x72D0 — COMMENTED** [review]
Don't we sacifice the modularity of this proc by removing AUV7.yaml and AUV8.yaml? Wouldn't be better to just keep those exactly the same?

**Review by 0x72D0 — COMMENTED** [review]
All the code you put in comment is it for a futur implementation?

**Comment by supertoto29** [comment]
@0x72D0 no the code won't be used and is already removed in the other branch

**Review by 0x72D0 — APPROVED** [review]
LGTM! but I the comment should not be there in the final version

**Review by alecst-marseille — APPROVED** [review]

**Pull request merged**
